spring:
  application:
    name: "spring-ai-llama-chat"
  ai:
    ollama:
      base-url: http://localhost:11434/
      chat:
        options:
          model: llama3.1
      embedding:
        enabled: true
        options:
          model: llama3.1

server:
  port: 8100

file:
  path: classpath:data/info.txt

logging:
  pattern:
    console: "%m%n"
